export const Requisiti = [
  'PHP',
  'MySql',
  'Wordpress',
  'Magento',
  'React-Native',
  'React',
  'HTML',
  'CSS',
  'JavaScript',
  'Python',
  'Linguaggio Di Programmazione Orientato Agli Oggetti',
  'Abilità di Presentazione',
  'Abilità di Vendite',
  'Lavoro di Squadra',
  'Illustrator',
  'Adobe Creative Cloud',
  'After Effects',
  'Logic Pro x',
];
